name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Lint with black
              run: |
                  black --check .
    deploy:
        runs-on: ubuntu-latest
        environment: diskution
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.10

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Copy GitHub secrets to file
              run: |
                  echo '${{ toJson(secrets) }}' > env_vars.json

            - name: Login to Heroku
              uses: akhileshns/heroku-deploy@v3.5.7 # This action deploys to Heroku
              with:
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: 'your-app-name' # Change this to your Heroku app name
                  heroku_email: 'your-email@example.com' # Change this to your Heroku email

            - name: Set Heroku Config Vars
              run: |
                  heroku plugins:install heroku-config
                  heroku config:push --app your-app-name --file env_vars.json

            - name: Deploy to Heroku
              run: |
                  git push heroku main
